"""bucle de verificacion

Revision ID: e03a4e9c52e5
Revises: 14d08e68b918
Create Date: 2026-09-07 01:57:14.546015
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "e03a4e9c52e5"
down_revision: Union[str, None] = "14d08e68b918"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "missions",
        sa.Column("mission_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("base_xp", sa.Integer(), nullable=False),
        sa.Column("required_rank", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("ground_truth", sa.String(length=16), nullable=False),
        sa.Column("truth_source", sa.String(length=24), nullable=True),
        sa.Column("source_confidence", sa.Integer(), nullable=False),
        sa.Column("independent_sources", sa.Integer(), nullable=False),
        sa.Column("kev_listed", sa.Boolean(), nullable=False),
        sa.Column(
            "first_reported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolves_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ground_truth IN ('MALICIOUS','BENIGN','UNKNOWN')",
            name="ck_ground_truth_valido",
        ),
        sa.PrimaryKeyConstraint("mission_id"),
    )
    op.create_index(
        op.f("ix_missions_ground_truth"), "missions", ["ground_truth"], unique=False
    )
    op.create_table(
        "verdicts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("analyst_id", sa.UUID(), nullable=False),
        sa.Column("mission_id", sa.String(length=32), nullable=False),
        sa.Column("call", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("brier_score", sa.Float(), nullable=True),
        sa.Column("xp_awarded", sa.Integer(), nullable=True),
        sa.Column("was_correct", sa.Boolean(), nullable=True),
        sa.CheckConstraint(
            "call IN ('MALICIOUS','BENIGN','INCONCLUSIVE')", name="ck_call_valido"
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 50 AND 100", name="ck_confianza_en_rango"
        ),
        sa.ForeignKeyConstraint(["analyst_id"], ["analysts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["mission_id"], ["missions.mission_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "analyst_id", "mission_id", name="uq_un_veredicto_por_mision"
        ),
    )
    op.create_index(
        "ix_verdicts_sin_calificar",
        "verdicts",
        ["mission_id"],
        unique=False,
        postgresql_where=sa.text("graded_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_verdicts_sin_calificar",
        table_name="verdicts",
        postgresql_where=sa.text("graded_at IS NULL"),
    )
    op.drop_table("verdicts")
    op.drop_index(op.f("ix_missions_ground_truth"), table_name="missions")
    op.drop_table("missions")
    # ### end Alembic commands ###
