"""avistamientos de indicadores

Revision ID: bc14549a9a84
Revises: 9bb64708c34e
Create Date: 2026-09-09 02:34:01.146299
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "bc14549a9a84"
down_revision: Union[str, None] = "9bb64708c34e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indicator_sightings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("mission_id", sa.String(length=32), nullable=False),
        sa.Column("fingerprint", sa.String(length=512), nullable=False),
        sa.Column("source_name", sa.String(length=64), nullable=False),
        sa.Column("source_family", sa.String(length=32), nullable=False),
        sa.Column("source_reference", sa.String(length=512), nullable=True),
        sa.Column("source_confidence", sa.Integer(), nullable=False),
        sa.Column("first_reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sample_available", sa.Boolean(), nullable=False),
        sa.Column("kev_listed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"], ["missions.mission_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mission_id", "source_name", name="uq_sighting_por_fuente"),
    )
    op.create_index(
        op.f("ix_indicator_sightings_fingerprint"),
        "indicator_sightings",
        ["fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_indicator_sightings_mission_id"),
        "indicator_sightings",
        ["mission_id"],
        unique=False,
    )
    op.add_column(
        "missions", sa.Column("fingerprint", sa.String(length=512), nullable=True)
    )
    op.create_index(
        op.f("ix_missions_fingerprint"), "missions", ["fingerprint"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_missions_fingerprint"), table_name="missions")
    op.drop_column("missions", "fingerprint")
    op.drop_index(
        op.f("ix_indicator_sightings_mission_id"), table_name="indicator_sightings"
    )
    op.drop_index(
        op.f("ix_indicator_sightings_fingerprint"), table_name="indicator_sightings"
    )
    op.drop_table("indicator_sightings")
    # ### end Alembic commands ###
