"""Identidad, credenciales y sesiones revocables.

Las columnas NOT NULL llevan `server_default` a propósito: sin él, aplicar
esta migración sobre una tabla `analysts` que YA tiene filas falla con
"column contains null values" — y falla después de haber tomado el lock de
la tabla, o sea con la aplicación ya degradada. Con la tabla vacía nunca se
nota; en producción, siempre.

Revision ID: 9bb64708c34e
Revises: e03a4e9c52e5
Create Date: 2026-09-08 23:28:37.793247
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "9bb64708c34e"
down_revision: Union[str, None] = "e03a4e9c52e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("analyst_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["analyst_id"], ["analysts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_analyst_id"),
        "refresh_tokens",
        ["analyst_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        "ix_refresh_vigentes",
        "refresh_tokens",
        ["analyst_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.add_column(
        "analysts", sa.Column("password_hash", sa.String(length=255), nullable=True)
    )
    op.add_column("analysts", sa.Column("email", sa.String(length=254), nullable=True))
    op.add_column(
        "analysts",
        sa.Column(
            "role", sa.String(length=16), nullable=False, server_default="ANALYST"
        ),
    )
    op.add_column(
        "analysts",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        "analysts",
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "analysts",
        sa.Column(
            "failed_login_attempts", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "analysts", sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_unique_constraint("uq_analysts_email", "analysts", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_analysts_email", "analysts", type_="unique")
    op.drop_column("analysts", "locked_until")
    op.drop_column("analysts", "failed_login_attempts")
    op.drop_column("analysts", "last_login_at")
    op.drop_column("analysts", "is_active")
    op.drop_column("analysts", "role")
    op.drop_column("analysts", "email")
    op.drop_column("analysts", "password_hash")
    op.drop_index(
        "ix_refresh_vigentes",
        table_name="refresh_tokens",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_analyst_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
