"""contenido de las misiones

Revision ID: e361543c513f
Revises: bc14549a9a84
Create Date: 2026-09-10 22:52:46.483227
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "e361543c513f"
down_revision: Union[str, None] = "bc14549a9a84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "missions",
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_index(
        "ix_missions_recientes",
        "missions",
        [sa.literal_column("first_reported_at DESC"), "mission_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_missions_recientes", table_name="missions")
    op.drop_column("missions", "payload")
    # ### end Alembic commands ###
